### ISSUE TITLE
Initial ideas for the talk

### ISSUE THREAD

**Issue by fejes713** [fejes713/github-universe-talk#1]
**I didn't get to this point alone** so I'd like to invite all awesome folks who contributed to @30-seconds organization (especially @Chalarangelo) to help me prepare the talk for [**GitHub Universe 2019**](https://githubuniverse.com). 

#### Checklist: 
⏳**deadline:** _24th October_

- [x] Discuss talk ideas
- [ ] Make slides
- [ ] Practice
- [ ] Practice
- [ ] Practice

I imagined my talk to be a collaborative process between everyone at @30-seconds so that's why I am asking for your input 😄 

Let's discuss the ideas in this thread below! :octocat:

**Comment by lacabra** [comment]
@fejes713 I attended your talk today at Github Universe, and I very much appreciated your great presentation. It was well-crafted, well-delivered, entertaining, insightful and actionable. Thanks for sharing your knowledge, and everyone else for contributing. ❤️OSS

**Comment by fejes713** [comment]
Wow! Thank you so much for the feedback @lacabra ❤️ :octocat: We all appreciate it.

**Comment by fejes713** [comment]
It's time to close this (until next time!), thank you so much for all the nice feedback and useful help. ❤️
